name: Claude PR Agent Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install anthropic python-dotenv

      - name: Get PR diff
        id: diff
        run: |
          git diff origin/${{ github.base_ref }}...HEAD > pr_diff.txt
          echo "Diff saved to pr_diff.txt"

      - name: Claude Code Review
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          python - <<'EOF'
          import os
          from anthropic import Anthropic

          client = Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

          with open("pr_diff.txt", "r") as f:
              diff = f.read()

          system_prompt = """You are an expert code reviewer specializing in Python and agentic systems.
          Review the following PR diff and provide:
          1. Code quality assessment
          2. Potential bugs or issues
          3. Suggestions for improvement
          4. Security concerns
          5. Best practices recommendations

          Be constructive and specific."""

          response = client.messages.create(
              model="claude-3-5-sonnet-20241022",
              max_tokens=2000,
              system=system_prompt,
              messages=[{
                  "role": "user",
                  "content": f"Review this PR:\n\n```diff\n{diff[:100000]}\n```"
              }]
          )

          review = response.content[0].text

          # Save review
          with open("review.md", "w") as f:
              f.write(f"# Claude Code Review\n\n{review}")

          print("Review completed!")
          EOF

      - name: Post review as comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('review.md', 'utf8');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: review
            });